### ISSUE TITLE
panic: runtime error: slice bounds out of range 

### ISSUE THREAD

**Issue by Sina-Ghaderi** [Sina-Ghaderi/goshkan#2]
### Bug Description
panic occurs on google.com domains.. 
binary log output:
```
2022/02/04 19:50:30 CONNEC: connected to upstream server, address: golang.org:80
2022/02/04 19:50:40 CONNEC: connected to upstream server, address: google.com:80
panic: runtime error: slice bounds out of range [:4] with capacity 1

goroutine 126 [running]:
io.(*teeReader).Read(0xc000049600, {0xc0001b44c1, 0x65b1db, 0x1})
	/usr/lib/go-1.17/src/io/io.go:562 +0xa9
goshkan/ntcp.readOnly.Read(...)
	/home/sina/Documents/test/xc/goshkan/ntcp/ntcp.go:35
net/http.(*connReader).backgroundRead(0xc0001b44b0)
	/usr/lib/go-1.17/src/net/http/server.go:672 +0x3f
created by net/http.(*connReader).startBackgroundRead
	/usr/lib/go-1.17/src/net/http/server.go:668 +0xcf
```

**Comment by Sina-Ghaderi** [comment]
Fixed  on [1e07ca7](https://github.com/Sina-Ghaderi/goshkan/commit/1e07ca77a095d219428efeb917422a7460a224a3)
with new version [release goshkan-0.2.6](https://github.com/Sina-Ghaderi/goshkan/releases/latest)
